-- Create API schema
CREATE SCHEMA IF NOT EXISTS api;

-- ============================================
-- TABLES WITH RELATIONSHIPS
-- ============================================

-- Users table
CREATE TABLE api.users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  full_name VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Posts table (belongs to users)
CREATE TABLE api.posts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES api.users(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  content TEXT,
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  view_count INTEGER DEFAULT 0,
  published_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Comments table (belongs to posts and users)
CREATE TABLE api.comments (
  id SERIAL PRIMARY KEY,
  post_id INTEGER REFERENCES api.posts(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES api.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tags table
CREATE TABLE api.tags (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL
);

-- Post-Tags junction table
CREATE TABLE api.post_tags (
  post_id INTEGER REFERENCES api.posts(id) ON DELETE CASCADE,
  tag_id INTEGER REFERENCES api.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

-- Products table (for e-commerce testing)
CREATE TABLE api.products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  stock INTEGER DEFAULT 0,
  category VARCHAR(50),
  rating DECIMAL(3, 2) DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- INSERT 50 USERS
-- ============================================

INSERT INTO api.users (username, email, full_name, is_active) VALUES
  ('user1', 'user1@example.com', 'User 1 Name', true),
  ('user2', 'user2@example.com', 'User 2 Name', true),
  ('user3', 'user3@example.com', 'User 3 Name', true),
  ('user4', 'user4@example.com', 'User 4 Name', true),
  ('user5', 'user5@example.com', 'User 5 Name', false),
  ('user6', 'user6@example.com', 'User 6 Name', true),
  ('user7', 'user7@example.com', 'User 7 Name', true),
  ('user8', 'user8@example.com', 'User 8 Name', true),
  ('user9', 'user9@example.com', 'User 9 Name', true),
  ('user10', 'user10@example.com', 'User 10 Name', false),
  ('user11', 'user11@example.com', 'User 11 Name', true),
  ('user12', 'user12@example.com', 'User 12 Name', true),
  ('user13', 'user13@example.com', 'User 13 Name', true),
  ('user14', 'user14@example.com', 'User 14 Name', true),
  ('user15', 'user15@example.com', 'User 15 Name', false),
  ('user16', 'user16@example.com', 'User 16 Name', true),
  ('user17', 'user17@example.com', 'User 17 Name', true),
  ('user18', 'user18@example.com', 'User 18 Name', true),
  ('user19', 'user19@example.com', 'User 19 Name', true),
  ('user20', 'user20@example.com', 'User 20 Name', false),
  ('user21', 'user21@example.com', 'User 21 Name', true),
  ('user22', 'user22@example.com', 'User 22 Name', true),
  ('user23', 'user23@example.com', 'User 23 Name', true),
  ('user24', 'user24@example.com', 'User 24 Name', true),
  ('user25', 'user25@example.com', 'User 25 Name', false),
  ('user26', 'user26@example.com', 'User 26 Name', true),
  ('user27', 'user27@example.com', 'User 27 Name', true),
  ('user28', 'user28@example.com', 'User 28 Name', true),
  ('user29', 'user29@example.com', 'User 29 Name', true),
  ('user30', 'user30@example.com', 'User 30 Name', false),
  ('user31', 'user31@example.com', 'User 31 Name', true),
  ('user32', 'user32@example.com', 'User 32 Name', true),
  ('user33', 'user33@example.com', 'User 33 Name', true),
  ('user34', 'user34@example.com', 'User 34 Name', true),
  ('user35', 'user35@example.com', 'User 35 Name', false),
  ('user36', 'user36@example.com', 'User 36 Name', true),
  ('user37', 'user37@example.com', 'User 37 Name', true),
  ('user38', 'user38@example.com', 'User 38 Name', true),
  ('user39', 'user39@example.com', 'User 39 Name', true),
  ('user40', 'user40@example.com', 'User 40 Name', false),
  ('user41', 'user41@example.com', 'User 41 Name', true),
  ('user42', 'user42@example.com', 'User 42 Name', true),
  ('user43', 'user43@example.com', 'User 43 Name', true),
  ('user44', 'user44@example.com', 'User 44 Name', true),
  ('user45', 'user45@example.com', 'User 45 Name', false),
  ('user46', 'user46@example.com', 'User 46 Name', true),
  ('user47', 'user47@example.com', 'User 47 Name', true),
  ('user48', 'user48@example.com', 'User 48 Name', true),
  ('user49', 'user49@example.com', 'User 49 Name', true),
  ('user50', 'user50@example.com', 'User 50 Name', false);

-- ============================================
-- INSERT 100 POSTS
-- ============================================

INSERT INTO api.posts (user_id, title, content, status, view_count, published_at) VALUES
  (1, 'Advanced SQL Techniques - Part 1', 'This is the content for post 1. It contains detailed information about the topic.', 'published', 13, NOW() - INTERVAL '2 days'),
  (2, 'Building REST APIs - Part 2', 'This is the content for post 2. It contains detailed information about the topic.', 'published', 26, NOW() - INTERVAL '3 days'),
  (3, 'Docker for Beginners - Part 3', 'This is the content for post 3. It contains detailed information about the topic.', 'draft', 39, NULL),
  (4, 'Database Optimization Tips - Part 4', 'This is the content for post 4. It contains detailed information about the topic.', 'archived', 52, NULL),
  (5, 'Understanding Indexes - Part 5', 'This is the content for post 5. It contains detailed information about the topic.', 'published', 65, NOW() - INTERVAL '6 days'),
  (6, 'Query Performance Tuning - Part 6', 'This is the content for post 6. It contains detailed information about the topic.', 'published', 78, NOW() - INTERVAL '7 days'),
  (7, 'Introduction to PostgREST - Part 7', 'This is the content for post 7. It contains detailed information about the topic.', 'published', 91, NOW() - INTERVAL '8 days'),
  (8, 'Web Development Best Practices - Part 8', 'This is the content for post 8. It contains detailed information about the topic.', 'draft', 104, NULL),
  (9, 'Security in Databases - Part 9', 'This is the content for post 9. It contains detailed information about the topic.', 'archived', 117, NULL),
  (10, 'Getting Started with PostgreSQL - Part 10', 'This is the content for post 10. It contains detailed information about the topic.', 'published', 130, NOW() - INTERVAL '11 days'),
  (11, 'Advanced SQL Techniques - Part 11', 'This is the content for post 11. It contains detailed information about the topic.', 'published', 143, NOW() - INTERVAL '12 days'),
  (12, 'Building REST APIs - Part 12', 'This is the content for post 12. It contains detailed information about the topic.', 'published', 156, NOW() - INTERVAL '13 days'),
  (13, 'Docker for Beginners - Part 13', 'This is the content for post 13. It contains detailed information about the topic.', 'draft', 169, NULL),
  (14, 'Database Optimization Tips - Part 14', 'This is the content for post 14. It contains detailed information about the topic.', 'archived', 182, NULL),
  (15, 'Understanding Indexes - Part 15', 'This is the content for post 15. It contains detailed information about the topic.', 'published', 195, NOW() - INTERVAL '16 days'),
  (16, 'Query Performance Tuning - Part 16', 'This is the content for post 16. It contains detailed information about the topic.', 'published', 208, NOW() - INTERVAL '17 days'),
  (17, 'Introduction to PostgREST - Part 17', 'This is the content for post 17. It contains detailed information about the topic.', 'published', 221, NOW() - INTERVAL '18 days'),
  (18, 'Web Development Best Practices - Part 18', 'This is the content for post 18. It contains detailed information about the topic.', 'draft', 234, NULL),
  (19, 'Security in Databases - Part 19', 'This is the content for post 19. It contains detailed information about the topic.', 'archived', 247, NULL),
  (20, 'Getting Started with PostgreSQL - Part 20', 'This is the content for post 20. It contains detailed information about the topic.', 'published', 260, NOW() - INTERVAL '21 days'),
  (21, 'Advanced SQL Techniques - Part 21', 'This is the content for post 21. It contains detailed information about the topic.', 'published', 273, NOW() - INTERVAL '22 days'),
  (22, 'Building REST APIs - Part 22', 'This is the content for post 22. It contains detailed information about the topic.', 'published', 286, NOW() - INTERVAL '23 days'),
  (23, 'Docker for Beginners - Part 23', 'This is the content for post 23. It contains detailed information about the topic.', 'draft', 299, NULL),
  (24, 'Database Optimization Tips - Part 24', 'This is the content for post 24. It contains detailed information about the topic.', 'archived', 312, NULL),
  (25, 'Understanding Indexes - Part 25', 'This is the content for post 25. It contains detailed information about the topic.', 'published', 325, NOW() - INTERVAL '26 days'),
  (26, 'Query Performance Tuning - Part 26', 'This is the content for post 26. It contains detailed information about the topic.', 'published', 338, NOW() - INTERVAL '27 days'),
  (27, 'Introduction to PostgREST - Part 27', 'This is the content for post 27. It contains detailed information about the topic.', 'published', 351, NOW() - INTERVAL '28 days'),
  (28, 'Web Development Best Practices - Part 28', 'This is the content for post 28. It contains detailed information about the topic.', 'draft', 364, NULL),
  (29, 'Security in Databases - Part 29', 'This is the content for post 29. It contains detailed information about the topic.', 'archived', 377, NULL),
  (30, 'Getting Started with PostgreSQL - Part 30', 'This is the content for post 30. It contains detailed information about the topic.', 'published', 390, NOW() - INTERVAL '1 days'),
  (31, 'Advanced SQL Techniques - Part 31', 'This is the content for post 31. It contains detailed information about the topic.', 'published', 403, NOW() - INTERVAL '2 days'),
  (32, 'Building REST APIs - Part 32', 'This is the content for post 32. It contains detailed information about the topic.', 'published', 416, NOW() - INTERVAL '3 days'),
  (33, 'Docker for Beginners - Part 33', 'This is the content for post 33. It contains detailed information about the topic.', 'draft', 429, NULL),
  (34, 'Database Optimization Tips - Part 34', 'This is the content for post 34. It contains detailed information about the topic.', 'archived', 442, NULL),
  (35, 'Understanding Indexes - Part 35', 'This is the content for post 35. It contains detailed information about the topic.', 'published', 455, NOW() - INTERVAL '6 days'),
  (36, 'Query Performance Tuning - Part 36', 'This is the content for post 36. It contains detailed information about the topic.', 'published', 468, NOW() - INTERVAL '7 days'),
  (37, 'Introduction to PostgREST - Part 37', 'This is the content for post 37. It contains detailed information about the topic.', 'published', 481, NOW() - INTERVAL '8 days'),
  (38, 'Web Development Best Practices - Part 38', 'This is the content for post 38. It contains detailed information about the topic.', 'draft', 494, NULL),
  (39, 'Security in Databases - Part 39', 'This is the content for post 39. It contains detailed information about the topic.', 'archived', 7, NULL),
  (40, 'Getting Started with PostgreSQL - Part 40', 'This is the content for post 40. It contains detailed information about the topic.', 'published', 20, NOW() - INTERVAL '11 days'),
  (41, 'Advanced SQL Techniques - Part 41', 'This is the content for post 41. It contains detailed information about the topic.', 'published', 33, NOW() - INTERVAL '12 days'),
  (42, 'Building REST APIs - Part 42', 'This is the content for post 42. It contains detailed information about the topic.', 'published', 46, NOW() - INTERVAL '13 days'),
  (43, 'Docker for Beginners - Part 43', 'This is the content for post 43. It contains detailed information about the topic.', 'draft', 59, NULL),
  (44, 'Database Optimization Tips - Part 44', 'This is the content for post 44. It contains detailed information about the topic.', 'archived', 72, NULL),
  (45, 'Understanding Indexes - Part 45', 'This is the content for post 45. It contains detailed information about the topic.', 'published', 85, NOW() - INTERVAL '16 days'),
  (46, 'Query Performance Tuning - Part 46', 'This is the content for post 46. It contains detailed information about the topic.', 'published', 98, NOW() - INTERVAL '17 days'),
  (47, 'Introduction to PostgREST - Part 47', 'This is the content for post 47. It contains detailed information about the topic.', 'published', 111, NOW() - INTERVAL '18 days'),
  (48, 'Web Development Best Practices - Part 48', 'This is the content for post 48. It contains detailed information about the topic.', 'draft', 124, NULL),
  (49, 'Security in Databases - Part 49', 'This is the content for post 49. It contains detailed information about the topic.', 'archived', 137, NULL),
  (50, 'Getting Started with PostgreSQL - Part 50', 'This is the content for post 50. It contains detailed information about the topic.', 'published', 150, NOW() - INTERVAL '21 days'),
  (1, 'Advanced SQL Techniques - Part 51', 'This is the content for post 51. It contains detailed information about the topic.', 'published', 163, NOW() - INTERVAL '22 days'),
  (2, 'Building REST APIs - Part 52', 'This is the content for post 52. It contains detailed information about the topic.', 'published', 176, NOW() - INTERVAL '23 days'),
  (3, 'Docker for Beginners - Part 53', 'This is the content for post 53. It contains detailed information about the topic.', 'draft', 189, NULL),
  (4, 'Database Optimization Tips - Part 54', 'This is the content for post 54. It contains detailed information about the topic.', 'archived', 202, NULL),
  (5, 'Understanding Indexes - Part 55', 'This is the content for post 55. It contains detailed information about the topic.', 'published', 215, NOW() - INTERVAL '26 days'),
  (6, 'Query Performance Tuning - Part 56', 'This is the content for post 56. It contains detailed information about the topic.', 'published', 228, NOW() - INTERVAL '27 days'),
  (7, 'Introduction to PostgREST - Part 57', 'This is the content for post 57. It contains detailed information about the topic.', 'published', 241, NOW() - INTERVAL '28 days'),
  (8, 'Web Development Best Practices - Part 58', 'This is the content for post 58. It contains detailed information about the topic.', 'draft', 254, NULL),
  (9, 'Security in Databases - Part 59', 'This is the content for post 59. It contains detailed information about the topic.', 'archived', 267, NULL),
  (10, 'Getting Started with PostgreSQL - Part 60', 'This is the content for post 60. It contains detailed information about the topic.', 'published', 280, NOW() - INTERVAL '1 days'),
  (11, 'Advanced SQL Techniques - Part 61', 'This is the content for post 61. It contains detailed information about the topic.', 'published', 293, NOW() - INTERVAL '2 days'),
  (12, 'Building REST APIs - Part 62', 'This is the content for post 62. It contains detailed information about the topic.', 'published', 306, NOW() - INTERVAL '3 days'),
  (13, 'Docker for Beginners - Part 63', 'This is the content for post 63. It contains detailed information about the topic.', 'draft', 319, NULL),
  (14, 'Database Optimization Tips - Part 64', 'This is the content for post 64. It contains detailed information about the topic.', 'archived', 332, NULL),
  (15, 'Understanding Indexes - Part 65', 'This is the content for post 65. It contains detailed information about the topic.', 'published', 345, NOW() - INTERVAL '6 days'),
  (16, 'Query Performance Tuning - Part 66', 'This is the content for post 66. It contains detailed information about the topic.', 'published', 358, NOW() - INTERVAL '7 days'),
  (17, 'Introduction to PostgREST - Part 67', 'This is the content for post 67. It contains detailed information about the topic.', 'published', 371, NOW() - INTERVAL '8 days'),
  (18, 'Web Development Best Practices - Part 68', 'This is the content for post 68. It contains detailed information about the topic.', 'draft', 384, NULL),
  (19, 'Security in Databases - Part 69', 'This is the content for post 69. It contains detailed information about the topic.', 'archived', 397, NULL),
  (20, 'Getting Started with PostgreSQL - Part 70', 'This is the content for post 70. It contains detailed information about the topic.', 'published', 410, NOW() - INTERVAL '11 days'),
  (21, 'Advanced SQL Techniques - Part 71', 'This is the content for post 71. It contains detailed information about the topic.', 'published', 423, NOW() - INTERVAL '12 days'),
  (22, 'Building REST APIs - Part 72', 'This is the content for post 72. It contains detailed information about the topic.', 'published', 436, NOW() - INTERVAL '13 days'),
  (23, 'Docker for Beginners - Part 73', 'This is the content for post 73. It contains detailed information about the topic.', 'draft', 449, NULL),
  (24, 'Database Optimization Tips - Part 74', 'This is the content for post 74. It contains detailed information about the topic.', 'archived', 462, NULL),
  (25, 'Understanding Indexes - Part 75', 'This is the content for post 75. It contains detailed information about the topic.', 'published', 475, NOW() - INTERVAL '16 days'),
  (26, 'Query Performance Tuning - Part 76', 'This is the content for post 76. It contains detailed information about the topic.', 'published', 488, NOW() - INTERVAL '17 days'),
  (27, 'Introduction to PostgREST - Part 77', 'This is the content for post 77. It contains detailed information about the topic.', 'published', 1, NOW() - INTERVAL '18 days'),
  (28, 'Web Development Best Practices - Part 78', 'This is the content for post 78. It contains detailed information about the topic.', 'draft', 14, NULL),
  (29, 'Security in Databases - Part 79', 'This is the content for post 79. It contains detailed information about the topic.', 'archived', 27, NULL),
  (30, 'Getting Started with PostgreSQL - Part 80', 'This is the content for post 80. It contains detailed information about the topic.', 'published', 40, NOW() - INTERVAL '21 days'),
  (31, 'Advanced SQL Techniques - Part 81', 'This is the content for post 81. It contains detailed information about the topic.', 'published', 53, NOW() - INTERVAL '22 days'),
  (32, 'Building REST APIs - Part 82', 'This is the content for post 82. It contains detailed information about the topic.', 'published', 66, NOW() - INTERVAL '23 days'),
  (33, 'Docker for Beginners - Part 83', 'This is the content for post 83. It contains detailed information about the topic.', 'draft', 79, NULL),
  (34, 'Database Optimization Tips - Part 84', 'This is the content for post 84. It contains detailed information about the topic.', 'archived', 92, NULL),
  (35, 'Understanding Indexes - Part 85', 'This is the content for post 85. It contains detailed information about the topic.', 'published', 105, NOW() - INTERVAL '26 days'),
  (36, 'Query Performance Tuning - Part 86', 'This is the content for post 86. It contains detailed information about the topic.', 'published', 118, NOW() - INTERVAL '27 days'),
  (37, 'Introduction to PostgREST - Part 87', 'This is the content for post 87. It contains detailed information about the topic.', 'published', 131, NOW() - INTERVAL '28 days'),
  (38, 'Web Development Best Practices - Part 88', 'This is the content for post 88. It contains detailed information about the topic.', 'draft', 144, NULL),
  (39, 'Security in Databases - Part 89', 'This is the content for post 89. It contains detailed information about the topic.', 'archived', 157, NULL),
  (40, 'Getting Started with PostgreSQL - Part 90', 'This is the content for post 90. It contains detailed information about the topic.', 'published', 170, NOW() - INTERVAL '1 days'),
  (41, 'Advanced SQL Techniques - Part 91', 'This is the content for post 91. It contains detailed information about the topic.', 'published', 183, NOW() - INTERVAL '2 days'),
  (42, 'Building REST APIs - Part 92', 'This is the content for post 92. It contains detailed information about the topic.', 'published', 196, NOW() - INTERVAL '3 days'),
  (43, 'Docker for Beginners - Part 93', 'This is the content for post 93. It contains detailed information about the topic.', 'draft', 209, NULL),
  (44, 'Database Optimization Tips - Part 94', 'This is the content for post 94. It contains detailed information about the topic.', 'archived', 222, NULL),
  (45, 'Understanding Indexes - Part 95', 'This is the content for post 95. It contains detailed information about the topic.', 'published', 235, NOW() - INTERVAL '6 days'),
  (46, 'Query Performance Tuning - Part 96', 'This is the content for post 96. It contains detailed information about the topic.', 'published', 248, NOW() - INTERVAL '7 days'),
  (47, 'Introduction to PostgREST - Part 97', 'This is the content for post 97. It contains detailed information about the topic.', 'published', 261, NOW() - INTERVAL '8 days'),
  (48, 'Web Development Best Practices - Part 98', 'This is the content for post 98. It contains detailed information about the topic.', 'draft', 274, NULL),
  (49, 'Security in Databases - Part 99', 'This is the content for post 99. It contains detailed information about the topic.', 'archived', 287, NULL),
  (50, 'Getting Started with PostgreSQL - Part 100', 'This is the content for post 100. It contains detailed information about the topic.', 'published', 300, NOW() - INTERVAL '11 days');

-- ============================================
-- INSERT 200 COMMENTS
-- ============================================

INSERT INTO api.comments (post_id, user_id, content) VALUES
  (1, 1, 'Very helpful, thanks!'),
  (2, 2, 'Learned a lot from this'),
  (3, 3, 'Can you elaborate more on this topic?'),
  (4, 4, 'Excellent explanation'),
  (5, 5, 'This solved my problem!'),
  (6, 6, 'Looking forward to more posts'),
  (7, 7, 'Could you provide more examples?'),
  (8, 8, 'Amazing content!'),
  (9, 9, 'Well written and informative'),
  (10, 10, 'Great article!'),
  (11, 11, 'Very helpful, thanks!'),
  (12, 12, 'Learned a lot from this'),
  (13, 13, 'Can you elaborate more on this topic?'),
  (14, 14, 'Excellent explanation'),
  (15, 15, 'This solved my problem!'),
  (16, 16, 'Looking forward to more posts'),
  (17, 17, 'Could you provide more examples?'),
  (18, 18, 'Amazing content!'),
  (19, 19, 'Well written and informative'),
  (20, 20, 'Great article!'),
  (21, 21, 'Very helpful, thanks!'),
  (22, 22, 'Learned a lot from this'),
  (23, 23, 'Can you elaborate more on this topic?'),
  (24, 24, 'Excellent explanation'),
  (25, 25, 'This solved my problem!'),
  (26, 26, 'Looking forward to more posts'),
  (27, 27, 'Could you provide more examples?'),
  (28, 28, 'Amazing content!'),
  (29, 29, 'Well written and informative'),
  (30, 30, 'Great article!'),
  (31, 31, 'Very helpful, thanks!'),
  (32, 32, 'Learned a lot from this'),
  (33, 33, 'Can you elaborate more on this topic?'),
  (34, 34, 'Excellent explanation'),
  (35, 35, 'This solved my problem!'),
  (36, 36, 'Looking forward to more posts'),
  (37, 37, 'Could you provide more examples?'),
  (38, 38, 'Amazing content!'),
  (39, 39, 'Well written and informative'),
  (40, 40, 'Great article!'),
  (41, 41, 'Very helpful, thanks!'),
  (42, 42, 'Learned a lot from this'),
  (43, 43, 'Can you elaborate more on this topic?'),
  (44, 44, 'Excellent explanation'),
  (45, 45, 'This solved my problem!'),
  (46, 46, 'Looking forward to more posts'),
  (47, 47, 'Could you provide more examples?'),
  (48, 48, 'Amazing content!'),
  (49, 49, 'Well written and informative'),
  (50, 50, 'Great article!'),
  (51, 1, 'Very helpful, thanks!'),
  (52, 2, 'Learned a lot from this'),
  (53, 3, 'Can you elaborate more on this topic?'),
  (54, 4, 'Excellent explanation'),
  (55, 5, 'This solved my problem!'),
  (56, 6, 'Looking forward to more posts'),
  (57, 7, 'Could you provide more examples?'),
  (58, 8, 'Amazing content!'),
  (59, 9, 'Well written and informative'),
  (60, 10, 'Great article!'),
  (61, 11, 'Very helpful, thanks!'),
  (62, 12, 'Learned a lot from this'),
  (63, 13, 'Can you elaborate more on this topic?'),
  (64, 14, 'Excellent explanation'),
  (65, 15, 'This solved my problem!'),
  (66, 16, 'Looking forward to more posts'),
  (67, 17, 'Could you provide more examples?'),
  (68, 18, 'Amazing content!'),
  (69, 19, 'Well written and informative'),
  (70, 20, 'Great article!'),
  (71, 21, 'Very helpful, thanks!'),
  (72, 22, 'Learned a lot from this'),
  (73, 23, 'Can you elaborate more on this topic?'),
  (74, 24, 'Excellent explanation'),
  (75, 25, 'This solved my problem!'),
  (76, 26, 'Looking forward to more posts'),
  (77, 27, 'Could you provide more examples?'),
  (78, 28, 'Amazing content!'),
  (79, 29, 'Well written and informative'),
  (80, 30, 'Great article!'),
  (81, 31, 'Very helpful, thanks!'),
  (82, 32, 'Learned a lot from this'),
  (83, 33, 'Can you elaborate more on this topic?'),
  (84, 34, 'Excellent explanation'),
  (85, 35, 'This solved my problem!'),
  (86, 36, 'Looking forward to more posts'),
  (87, 37, 'Could you provide more examples?'),
  (88, 38, 'Amazing content!'),
  (89, 39, 'Well written and informative'),
  (90, 40, 'Great article!'),
  (91, 41, 'Very helpful, thanks!'),
  (92, 42, 'Learned a lot from this'),
  (93, 43, 'Can you elaborate more on this topic?'),
  (94, 44, 'Excellent explanation'),
  (95, 45, 'This solved my problem!'),
  (96, 46, 'Looking forward to more posts'),
  (97, 47, 'Could you provide more examples?'),
  (98, 48, 'Amazing content!'),
  (99, 49, 'Well written and informative'),
  (100, 50, 'Great article!'),
  (1, 1, 'Very helpful, thanks!'),
  (2, 2, 'Learned a lot from this'),
  (3, 3, 'Can you elaborate more on this topic?'),
  (4, 4, 'Excellent explanation'),
  (5, 5, 'This solved my problem!'),
  (6, 6, 'Looking forward to more posts'),
  (7, 7, 'Could you provide more examples?'),
  (8, 8, 'Amazing content!'),
  (9, 9, 'Well written and informative'),
  (10, 10, 'Great article!'),
  (11, 11, 'Very helpful, thanks!'),
  (12, 12, 'Learned a lot from this'),
  (13, 13, 'Can you elaborate more on this topic?'),
  (14, 14, 'Excellent explanation'),
  (15, 15, 'This solved my problem!'),
  (16, 16, 'Looking forward to more posts'),
  (17, 17, 'Could you provide more examples?'),
  (18, 18, 'Amazing content!'),
  (19, 19, 'Well written and informative'),
  (20, 20, 'Great article!'),
  (21, 21, 'Very helpful, thanks!'),
  (22, 22, 'Learned a lot from this'),
  (23, 23, 'Can you elaborate more on this topic?'),
  (24, 24, 'Excellent explanation'),
  (25, 25, 'This solved my problem!'),
  (26, 26, 'Looking forward to more posts'),
  (27, 27, 'Could you provide more examples?'),
  (28, 28, 'Amazing content!'),
  (29, 29, 'Well written and informative'),
  (30, 30, 'Great article!'),
  (31, 31, 'Very helpful, thanks!'),
  (32, 32, 'Learned a lot from this'),
  (33, 33, 'Can you elaborate more on this topic?'),
  (34, 34, 'Excellent explanation'),
  (35, 35, 'This solved my problem!'),
  (36, 36, 'Looking forward to more posts'),
  (37, 37, 'Could you provide more examples?'),
  (38, 38, 'Amazing content!'),
  (39, 39, 'Well written and informative'),
  (40, 40, 'Great article!'),
  (41, 41, 'Very helpful, thanks!'),
  (42, 42, 'Learned a lot from this'),
  (43, 43, 'Can you elaborate more on this topic?'),
  (44, 44, 'Excellent explanation'),
  (45, 45, 'This solved my problem!'),
  (46, 46, 'Looking forward to more posts'),
  (47, 47, 'Could you provide more examples?'),
  (48, 48, 'Amazing content!'),
  (49, 49, 'Well written and informative'),
  (50, 50, 'Great article!'),
  (51, 1, 'Very helpful, thanks!'),
  (52, 2, 'Learned a lot from this'),
  (53, 3, 'Can you elaborate more on this topic?'),
  (54, 4, 'Excellent explanation'),
  (55, 5, 'This solved my problem!'),
  (56, 6, 'Looking forward to more posts'),
  (57, 7, 'Could you provide more examples?'),
  (58, 8, 'Amazing content!'),
  (59, 9, 'Well written and informative'),
  (60, 10, 'Great article!'),
  (61, 11, 'Very helpful, thanks!'),
  (62, 12, 'Learned a lot from this'),
  (63, 13, 'Can you elaborate more on this topic?'),
  (64, 14, 'Excellent explanation'),
  (65, 15, 'This solved my problem!'),
  (66, 16, 'Looking forward to more posts'),
  (67, 17, 'Could you provide more examples?'),
  (68, 18, 'Amazing content!'),
  (69, 19, 'Well written and informative'),
  (70, 20, 'Great article!'),
  (71, 21, 'Very helpful, thanks!'),
  (72, 22, 'Learned a lot from this'),
  (73, 23, 'Can you elaborate more on this topic?'),
  (74, 24, 'Excellent explanation'),
  (75, 25, 'This solved my problem!'),
  (76, 26, 'Looking forward to more posts'),
  (77, 27, 'Could you provide more examples?'),
  (78, 28, 'Amazing content!'),
  (79, 29, 'Well written and informative'),
  (80, 30, 'Great article!'),
  (81, 31, 'Very helpful, thanks!'),
  (82, 32, 'Learned a lot from this'),
  (83, 33, 'Can you elaborate more on this topic?'),
  (84, 34, 'Excellent explanation'),
  (85, 35, 'This solved my problem!'),
  (86, 36, 'Looking forward to more posts'),
  (87, 37, 'Could you provide more examples?'),
  (88, 38, 'Amazing content!'),
  (89, 39, 'Well written and informative'),
  (90, 40, 'Great article!'),
  (91, 41, 'Very helpful, thanks!'),
  (92, 42, 'Learned a lot from this'),
  (93, 43, 'Can you elaborate more on this topic?'),
  (94, 44, 'Excellent explanation'),
  (95, 45, 'This solved my problem!'),
  (96, 46, 'Looking forward to more posts'),
  (97, 47, 'Could you provide more examples?'),
  (98, 48, 'Amazing content!'),
  (99, 49, 'Well written and informative'),
  (100, 50, 'Great article!');

-- ============================================
-- INSERT TAGS
-- ============================================

INSERT INTO api.tags (name) VALUES
  ('tutorial'), ('postgresql'), ('docker'), ('api'), ('performance'),
  ('security'), ('beginner'), ('advanced'), ('development'), ('optimization'),
  ('sql'), ('rest'), ('database'), ('web'), ('backend'),
  ('frontend'), ('javascript'), ('python'), ('nodejs'), ('devops');

-- ============================================
-- INSERT POST-TAG RELATIONSHIPS (300 records)
-- ============================================

INSERT INTO api.post_tags (post_id, tag_id) VALUES
  (1, 1),
  (1, 4),
  (1, 8),
  (2, 2),
  (2, 7),
  (2, 15),
  (3, 3),
  (3, 10),
  (3, 2),
  (4, 4),
  (4, 13),
  (4, 9),
  (5, 5),
  (5, 16),
  (6, 6),
  (6, 19),
  (6, 3),
  (7, 7),
  (7, 2),
  (7, 10),
  (8, 8),
  (8, 5),
  (8, 17),
  (9, 9),
  (9, 8),
  (9, 4),
  (10, 10),
  (10, 11),
  (11, 11),
  (11, 14),
  (11, 18),
  (12, 12),
  (12, 17),
  (12, 5),
  (13, 13),
  (13, 20),
  (13, 12),
  (14, 14),
  (14, 3),
  (14, 19),
  (15, 15),
  (15, 6),
  (16, 16),
  (16, 9),
  (16, 13),
  (17, 17),
  (17, 12),
  (17, 20),
  (18, 18),
  (18, 15),
  (18, 7),
  (19, 19),
  (19, 18),
  (19, 14),
  (20, 20),
  (20, 1),
  (21, 1),
  (21, 4),
  (21, 8),
  (22, 2),
  (22, 7),
  (22, 15),
  (23, 3),
  (23, 10),
  (23, 2),
  (24, 4),
  (24, 13),
  (24, 9),
  (25, 5),
  (25, 16),
  (26, 6),
  (26, 19),
  (26, 3),
  (27, 7),
  (27, 2),
  (27, 10),
  (28, 8),
  (28, 5),
  (28, 17),
  (29, 9),
  (29, 8),
  (29, 4),
  (30, 10),
  (30, 11),
  (31, 11),
  (31, 14),
  (31, 18),
  (32, 12),
  (32, 17),
  (32, 5),
  (33, 13),
  (33, 20),
  (33, 12),
  (34, 14),
  (34, 3),
  (34, 19),
  (35, 15),
  (35, 6),
  (36, 16),
  (36, 9),
  (36, 13),
  (37, 17),
  (37, 12),
  (37, 20),
  (38, 18),
  (38, 15),
  (38, 7),
  (39, 19),
  (39, 18),
  (39, 14),
  (40, 20),
  (40, 1),
  (41, 1),
  (41, 4),
  (41, 8),
  (42, 2),
  (42, 7),
  (42, 15),
  (43, 3),
  (43, 10),
  (43, 2),
  (44, 4),
  (44, 13),
  (44, 9),
  (45, 5),
  (45, 16),
  (46, 6),
  (46, 19),
  (46, 3),
  (47, 7),
  (47, 2),
  (47, 10),
  (48, 8),
  (48, 5),
  (48, 17),
  (49, 9),
  (49, 8),
  (49, 4),
  (50, 10),
  (50, 11),
  (51, 11),
  (51, 14),
  (51, 18),
  (52, 12),
  (52, 17),
  (52, 5),
  (53, 13),
  (53, 20),
  (53, 12),
  (54, 14),
  (54, 3),
  (54, 19),
  (55, 15),
  (55, 6),
  (56, 16),
  (56, 9),
  (56, 13),
  (57, 17),
  (57, 12),
  (57, 20),
  (58, 18),
  (58, 15),
  (58, 7),
  (59, 19),
  (59, 18),
  (59, 14),
  (60, 20),
  (60, 1),
  (61, 1),
  (61, 4),
  (61, 8),
  (62, 2),
  (62, 7),
  (62, 15),
  (63, 3),
  (63, 10),
  (63, 2),
  (64, 4),
  (64, 13),
  (64, 9),
  (65, 5),
  (65, 16),
  (66, 6),
  (66, 19),
  (66, 3),
  (67, 7),
  (67, 2),
  (67, 10),
  (68, 8),
  (68, 5),
  (68, 17),
  (69, 9),
  (69, 8),
  (69, 4),
  (70, 10),
  (70, 11),
  (71, 11),
  (71, 14),
  (71, 18),
  (72, 12),
  (72, 17),
  (72, 5),
  (73, 13),
  (73, 20),
  (73, 12),
  (74, 14),
  (74, 3),
  (74, 19),
  (75, 15),
  (75, 6),
  (76, 16),
  (76, 9),
  (76, 13),
  (77, 17),
  (77, 12),
  (77, 20),
  (78, 18),
  (78, 15),
  (78, 7),
  (79, 19),
  (79, 18),
  (79, 14),
  (80, 20),
  (80, 1),
  (81, 1),
  (81, 4),
  (81, 8),
  (82, 2),
  (82, 7),
  (82, 15),
  (83, 3),
  (83, 10),
  (83, 2),
  (84, 4),
  (84, 13),
  (84, 9),
  (85, 5),
  (85, 16),
  (86, 6),
  (86, 19),
  (86, 3),
  (87, 7),
  (87, 2),
  (87, 10),
  (88, 8),
  (88, 5),
  (88, 17),
  (89, 9),
  (89, 8),
  (89, 4),
  (90, 10),
  (90, 11),
  (91, 11),
  (91, 14),
  (91, 18),
  (92, 12),
  (92, 17),
  (92, 5),
  (93, 13),
  (93, 20),
  (93, 12),
  (94, 14),
  (94, 3),
  (94, 19),
  (95, 15),
  (95, 6),
  (96, 16),
  (96, 9),
  (96, 13),
  (97, 17),
  (97, 12),
  (97, 20),
  (98, 18),
  (98, 15),
  (98, 7),
  (99, 19),
  (99, 18),
  (99, 14),
  (100, 20),
  (100, 1);

-- ============================================
-- INSERT 100 PRODUCTS
-- ============================================

INSERT INTO api.products (name, description, price, stock, category, rating) VALUES
  ('USB-C Cable #1', 'High quality usb-c cable with excellent features', 13.44, 7, 'Books', 3.1),
  ('Mechanical Keyboard #2', 'High quality mechanical keyboard with excellent features', 16.89, 14, 'Clothing', 3.2),
  ('HD Monitor #3', 'High quality hd monitor with excellent features', 20.34, 21, 'Home & Garden', 3.3),
  ('Laptop Stand #4', 'High quality laptop stand with excellent features', 23.79, 28, 'Sports', 3.4),
  ('Desk Lamp #5', 'High quality desk lamp with excellent features', 27.24, 35, 'Toys', 3.5),
  ('Notebook Set #6', 'High quality notebook set with excellent features', 30.69, 42, 'Food', 3.6),
  ('Programming Book #7', 'High quality programming book with excellent features', 34.14, 49, 'Beauty', 3.7),
  ('Coffee Mug #8', 'High quality coffee mug with excellent features', 37.59, 56, 'Electronics', 3.8),
  ('Water Bottle #9', 'High quality water bottle with excellent features', 41.04, 63, 'Books', 3.9),
  ('Backpack #10', 'High quality backpack with excellent features', 44.49, 70, 'Clothing', 4.0),
  ('Phone Case #11', 'High quality phone case with excellent features', 47.94, 77, 'Home & Garden', 4.1),
  ('Headphones #12', 'High quality headphones with excellent features', 51.39, 84, 'Sports', 4.2),
  ('Webcam #13', 'High quality webcam with excellent features', 54.84, 91, 'Toys', 4.3),
  ('Microphone #14', 'High quality microphone with excellent features', 58.29, 98, 'Food', 4.4),
  ('Gaming Chair #15', 'High quality gaming chair with excellent features', 61.74, 105, 'Beauty', 4.5),
  ('Desk Organizer #16', 'High quality desk organizer with excellent features', 65.19, 112, 'Electronics', 4.6),
  ('Pen Set #17', 'High quality pen set with excellent features', 68.64, 119, 'Books', 4.7),
  ('Sticky Notes #18', 'High quality sticky notes with excellent features', 72.09, 126, 'Clothing', 4.8),
  ('Planner #19', 'High quality planner with excellent features', 75.54, 133, 'Home & Garden', 4.9),
  ('Premium Wireless Mouse #20', 'High quality premium wireless mouse with excellent features', 78.99, 140, 'Sports', 3.0),
  ('USB-C Cable #21', 'High quality usb-c cable with excellent features', 82.44, 147, 'Toys', 3.1),
  ('Mechanical Keyboard #22', 'High quality mechanical keyboard with excellent features', 85.89, 154, 'Food', 3.2),
  ('HD Monitor #23', 'High quality hd monitor with excellent features', 89.34, 161, 'Beauty', 3.3),
  ('Laptop Stand #24', 'High quality laptop stand with excellent features', 92.79, 168, 'Electronics', 3.4),
  ('Desk Lamp #25', 'High quality desk lamp with excellent features', 96.24, 175, 'Books', 3.5),
  ('Notebook Set #26', 'High quality notebook set with excellent features', 99.69, 182, 'Clothing', 3.6),
  ('Programming Book #27', 'High quality programming book with excellent features', 103.14, 189, 'Home & Garden', 3.7),
  ('Coffee Mug #28', 'High quality coffee mug with excellent features', 106.59, 196, 'Sports', 3.8),
  ('Water Bottle #29', 'High quality water bottle with excellent features', 110.04, 3, 'Toys', 3.9),
  ('Backpack #30', 'High quality backpack with excellent features', 113.49, 10, 'Food', 4.0),
  ('Phone Case #31', 'High quality phone case with excellent features', 116.94, 17, 'Beauty', 4.1),
  ('Headphones #32', 'High quality headphones with excellent features', 120.39, 24, 'Electronics', 4.2),
  ('Webcam #33', 'High quality webcam with excellent features', 123.84, 31, 'Books', 4.3),
  ('Microphone #34', 'High quality microphone with excellent features', 127.29, 38, 'Clothing', 4.4),
  ('Gaming Chair #35', 'High quality gaming chair with excellent features', 130.74, 45, 'Home & Garden', 4.5),
  ('Desk Organizer #36', 'High quality desk organizer with excellent features', 134.19, 52, 'Sports', 4.6),
  ('Pen Set #37', 'High quality pen set with excellent features', 137.64, 59, 'Toys', 4.7),
  ('Sticky Notes #38', 'High quality sticky notes with excellent features', 141.09, 66, 'Food', 4.8),
  ('Planner #39', 'High quality planner with excellent features', 144.54, 73, 'Beauty', 4.9),
  ('Premium Wireless Mouse #40', 'High quality premium wireless mouse with excellent features', 147.99, 80, 'Electronics', 3.0),
  ('USB-C Cable #41', 'High quality usb-c cable with excellent features', 151.44, 87, 'Books', 3.1),
  ('Mechanical Keyboard #42', 'High quality mechanical keyboard with excellent features', 154.89, 94, 'Clothing', 3.2),
  ('HD Monitor #43', 'High quality hd monitor with excellent features', 158.34, 101, 'Home & Garden', 3.3),
  ('Laptop Stand #44', 'High quality laptop stand with excellent features', 161.79, 108, 'Sports', 3.4),
  ('Desk Lamp #45', 'High quality desk lamp with excellent features', 165.24, 115, 'Toys', 3.5),
  ('Notebook Set #46', 'High quality notebook set with excellent features', 168.69, 122, 'Food', 3.6),
  ('Programming Book #47', 'High quality programming book with excellent features', 172.14, 129, 'Beauty', 3.7),
  ('Coffee Mug #48', 'High quality coffee mug with excellent features', 175.59, 136, 'Electronics', 3.8),
  ('Water Bottle #49', 'High quality water bottle with excellent features', 179.04, 143, 'Books', 3.9),
  ('Backpack #50', 'High quality backpack with excellent features', 182.49, 150, 'Clothing', 4.0),
  ('Phone Case #51', 'High quality phone case with excellent features', 185.94, 157, 'Home & Garden', 4.1),
  ('Headphones #52', 'High quality headphones with excellent features', 189.39, 164, 'Sports', 4.2),
  ('Webcam #53', 'High quality webcam with excellent features', 192.84, 171, 'Toys', 4.3),
  ('Microphone #54', 'High quality microphone with excellent features', 196.29, 178, 'Food', 4.4),
  ('Gaming Chair #55', 'High quality gaming chair with excellent features', 199.74, 185, 'Beauty', 4.5),
  ('Desk Organizer #56', 'High quality desk organizer with excellent features', 203.19, 192, 'Electronics', 4.6),
  ('Pen Set #57', 'High quality pen set with excellent features', 206.64, 199, 'Books', 4.7),
  ('Sticky Notes #58', 'High quality sticky notes with excellent features', 210.09, 6, 'Clothing', 4.8),
  ('Planner #59', 'High quality planner with excellent features', 213.54, 13, 'Home & Garden', 4.9),
  ('Premium Wireless Mouse #60', 'High quality premium wireless mouse with excellent features', 216.99, 20, 'Sports', 3.0),
  ('USB-C Cable #61', 'High quality usb-c cable with excellent features', 220.44, 27, 'Toys', 3.1),
  ('Mechanical Keyboard #62', 'High quality mechanical keyboard with excellent features', 223.89, 34, 'Food', 3.2),
  ('HD Monitor #63', 'High quality hd monitor with excellent features', 227.34, 41, 'Beauty', 3.3),
  ('Laptop Stand #64', 'High quality laptop stand with excellent features', 230.79, 48, 'Electronics', 3.4),
  ('Desk Lamp #65', 'High quality desk lamp with excellent features', 234.24, 55, 'Books', 3.5),
  ('Notebook Set #66', 'High quality notebook set with excellent features', 237.69, 62, 'Clothing', 3.6),
  ('Programming Book #67', 'High quality programming book with excellent features', 241.14, 69, 'Home & Garden', 3.7),
  ('Coffee Mug #68', 'High quality coffee mug with excellent features', 244.59, 76, 'Sports', 3.8),
  ('Water Bottle #69', 'High quality water bottle with excellent features', 248.04, 83, 'Toys', 3.9),
  ('Backpack #70', 'High quality backpack with excellent features', 251.49, 90, 'Food', 4.0),
  ('Phone Case #71', 'High quality phone case with excellent features', 254.94, 97, 'Beauty', 4.1),
  ('Headphones #72', 'High quality headphones with excellent features', 258.39, 104, 'Electronics', 4.2),
  ('Webcam #73', 'High quality webcam with excellent features', 261.84, 111, 'Books', 4.3),
  ('Microphone #74', 'High quality microphone with excellent features', 265.29, 118, 'Clothing', 4.4),
  ('Gaming Chair #75', 'High quality gaming chair with excellent features', 268.74, 125, 'Home & Garden', 4.5),
  ('Desk Organizer #76', 'High quality desk organizer with excellent features', 272.19, 132, 'Sports', 4.6),
  ('Pen Set #77', 'High quality pen set with excellent features', 275.64, 139, 'Toys', 4.7),
  ('Sticky Notes #78', 'High quality sticky notes with excellent features', 279.09, 146, 'Food', 4.8),
  ('Planner #79', 'High quality planner with excellent features', 282.54, 153, 'Beauty', 4.9),
  ('Premium Wireless Mouse #80', 'High quality premium wireless mouse with excellent features', 285.99, 160, 'Electronics', 3.0),
  ('USB-C Cable #81', 'High quality usb-c cable with excellent features', 289.44, 167, 'Books', 3.1),
  ('Mechanical Keyboard #82', 'High quality mechanical keyboard with excellent features', 292.89, 174, 'Clothing', 3.2),
  ('HD Monitor #83', 'High quality hd monitor with excellent features', 296.34, 181, 'Home & Garden', 3.3),
  ('Laptop Stand #84', 'High quality laptop stand with excellent features', 299.79, 188, 'Sports', 3.4),
  ('Desk Lamp #85', 'High quality desk lamp with excellent features', 303.24, 195, 'Toys', 3.5),
  ('Notebook Set #86', 'High quality notebook set with excellent features', 306.69, 2, 'Food', 3.6),
  ('Programming Book #87', 'High quality programming book with excellent features', 310.14, 9, 'Beauty', 3.7),
  ('Coffee Mug #88', 'High quality coffee mug with excellent features', 313.59, 16, 'Electronics', 3.8),
  ('Water Bottle #89', 'High quality water bottle with excellent features', 317.04, 23, 'Books', 3.9),
  ('Backpack #90', 'High quality backpack with excellent features', 320.49, 30, 'Clothing', 4.0),
  ('Phone Case #91', 'High quality phone case with excellent features', 323.94, 37, 'Home & Garden', 4.1),
  ('Headphones #92', 'High quality headphones with excellent features', 327.39, 44, 'Sports', 4.2),
  ('Webcam #93', 'High quality webcam with excellent features', 330.84, 51, 'Toys', 4.3),
  ('Microphone #94', 'High quality microphone with excellent features', 334.29, 58, 'Food', 4.4),
  ('Gaming Chair #95', 'High quality gaming chair with excellent features', 337.74, 65, 'Beauty', 4.5),
  ('Desk Organizer #96', 'High quality desk organizer with excellent features', 341.19, 72, 'Electronics', 4.6),
  ('Pen Set #97', 'High quality pen set with excellent features', 344.64, 79, 'Books', 4.7),
  ('Sticky Notes #98', 'High quality sticky notes with excellent features', 348.09, 86, 'Clothing', 4.8),
  ('Planner #99', 'High quality planner with excellent features', 351.54, 93, 'Home & Garden', 4.9),
  ('Premium Wireless Mouse #100', 'High quality premium wireless mouse with excellent features', 354.99, 100, 'Sports', 3.0);

-- ============================================
-- VIEWS
-- ============================================

-- View: Posts with user information
CREATE VIEW api.posts_with_authors AS
SELECT 
  p.id,
  p.title,
  p.content,
  p.status,
  p.view_count,
  p.published_at,
  u.username AS author_username,
  u.full_name AS author_name,
  (SELECT COUNT(*) FROM api.comments c WHERE c.post_id = p.id) AS comment_count
FROM api.posts p
JOIN api.users u ON p.user_id = u.id;

-- View: Popular posts (more than 100 views)
CREATE VIEW api.popular_posts AS
SELECT * FROM api.posts WHERE view_count > 100 ORDER BY view_count DESC;

-- View: Active users with their post count
CREATE VIEW api.active_users_stats AS
SELECT 
  u.id,
  u.username,
  u.email,
  u.full_name,
  COUNT(p.id) as post_count,
  SUM(p.view_count) as total_views
FROM api.users u
LEFT JOIN api.posts p ON u.id = p.user_id
WHERE u.is_active = true
GROUP BY u.id, u.username, u.email, u.full_name;

-- View: Products by category
CREATE VIEW api.products_by_category AS
SELECT 
  category,
  COUNT(*) as product_count,
  AVG(price) as avg_price,
  SUM(stock) as total_stock
FROM api.products
GROUP BY category;

-- ============================================
-- RPC FUNCTIONS
-- ============================================

-- Function: Search posts by keyword
CREATE OR REPLACE FUNCTION api.search_posts(keyword TEXT)
RETURNS SETOF api.posts AS $$
  SELECT * FROM api.posts 
  WHERE title ILIKE '%' || keyword || '%' 
     OR content ILIKE '%' || keyword || '%'
  ORDER BY view_count DESC;
$$ LANGUAGE SQL STABLE;

-- Function: Get post statistics
CREATE OR REPLACE FUNCTION api.post_stats()
RETURNS TABLE(
  total_posts BIGINT,
  published_posts BIGINT,
  draft_posts BIGINT,
  archived_posts BIGINT,
  total_views BIGINT,
  avg_views NUMERIC
) AS $$
  SELECT 
    COUNT(*) as total_posts,
    COUNT(*) FILTER (WHERE status = 'published') as published_posts,
    COUNT(*) FILTER (WHERE status = 'draft') as draft_posts,
    COUNT(*) FILTER (WHERE status = 'archived') as archived_posts,
    SUM(view_count) as total_views,
    ROUND(AVG(view_count), 2) as avg_views
  FROM api.posts;
$$ LANGUAGE SQL STABLE;

-- Function: Increment post view count
CREATE OR REPLACE FUNCTION api.increment_view_count(post_id INTEGER)
RETURNS api.posts AS $$
  UPDATE api.posts SET view_count = view_count + 1 
  WHERE id = post_id 
  RETURNING *;
$$ LANGUAGE SQL VOLATILE;

-- Function: Get user's posts with comment count
CREATE OR REPLACE FUNCTION api.get_user_posts(user_id INTEGER)
RETURNS TABLE(
  post_id INTEGER,
  title VARCHAR,
  status VARCHAR,
  view_count INTEGER,
  comment_count BIGINT,
  published_at TIMESTAMP
) AS $$
  SELECT 
    p.id,
    p.title,
    p.status,
    p.view_count,
    COUNT(c.id) as comment_count,
    p.published_at
  FROM api.posts p
  LEFT JOIN api.comments c ON p.id = c.post_id
  WHERE p.user_id = get_user_posts.user_id
  GROUP BY p.id, p.title, p.status, p.view_count, p.published_at
  ORDER BY p.created_at DESC;
$$ LANGUAGE SQL STABLE;

-- Function: Search products with filters
CREATE OR REPLACE FUNCTION api.search_products(
  min_price DECIMAL DEFAULT 0,
  max_price DECIMAL DEFAULT 999999,
  search_category VARCHAR DEFAULT NULL
)
RETURNS SETOF api.products AS $$
  SELECT * FROM api.products 
  WHERE price BETWEEN min_price AND max_price
    AND (search_category IS NULL OR category = search_category)
  ORDER BY rating DESC, price ASC;
$$ LANGUAGE SQL STABLE;

-- ============================================
-- ROLES AND PERMISSIONS
-- ============================================

-- Create web_anon role for unauthenticated requests
CREATE ROLE web_anon NOLOGIN;
GRANT USAGE ON SCHEMA api TO web_anon;

-- Read access to all tables
GRANT SELECT ON api.users, api.posts, api.comments, api.tags, api.post_tags, api.products TO web_anon;

-- Read access to views
GRANT SELECT ON api.posts_with_authors, api.popular_posts, api.active_users_stats, api.products_by_category TO web_anon;

-- Execute permissions for functions
GRANT EXECUTE ON FUNCTION api.search_posts(TEXT) TO web_anon;
GRANT EXECUTE ON FUNCTION api.post_stats() TO web_anon;
GRANT EXECUTE ON FUNCTION api.increment_view_count(INTEGER) TO web_anon;
GRANT EXECUTE ON FUNCTION api.get_user_posts(INTEGER) TO web_anon;
GRANT EXECUTE ON FUNCTION api.search_products(DECIMAL, DECIMAL, VARCHAR) TO web_anon;

-- Grant sequence access
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA api TO web_anon;
